# Generated by Django 4.1.7 on 2023-05-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mode',
        ),
    ]
